### PR TITLE
update label refresh option

### PR DESCRIPTION
**Pull request by dislbenn**
Related issue: https://github.com/open-cluster-management/backlog/issues/15324
Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

This PR updates the dashboard refresh option for `release-2.2`.

### CODE REVIEW

**Review by RobDolares — APPROVED** [review]
/lgtm

**Comment by dislbenn** [comment]
This PR is just a recreation of the previous one. The PR commits weren't signing off properly.

**Pull request merged**
