### PR TITLE
Added missing metrics to default metrics allowlist

### PR DESCRIPTION
**Pull request by dislbenn**
This will add the missing metrics that were listed from the issue: [#8853](https://github.com/open-cluster-management/backlog/issues/8853), into the default metric allowlist. For issue: [#11130](https://github.com/open-cluster-management/backlog/issues/11130), we need to add these metrics to ensure that all OOTB rules and metrics are being evaluated correctly.

Currently, we have: 
- 126 metrics present in the metrics allow-list
- 134 metrics missing from the metrics allow-list

In order to prevent having a large number of metrics within this list, we will need to determine which metric we need to include/exclude from the allow list. Because adding a ton of metrics will be very expensive.

### CODE REVIEW

**Comment by clyang82** [comment]
any impact on the performance? Could you list the number of timeseries for those metrics? Thanks

**Comment by dislbenn** [comment]
<details>
  <summary> Metrics Time Series Tables </summary>

| #   | Metric Name                                                           | Time Series |
| --- | ------------------------------------------------------------------ | ----------  |
| 1   | aggregator_unavailable_apiservice                                     | 219         |
| 2   | aggregator_unavailable_apiservice_count                               | 0           |
|3   | alertmanager_cluster_members                                          | 3           |
4   | alertmanager_config_hash                                              | 3           |
5   | alertmanager_config_last_reload_successful                            | 3           |
6   | apiserver_client_certificate_expiration_seconds_bucket                | 585         |
7   | apiserver_client_certificate_expiration_seconds_count                 | 39          |
8   | apiserver_request:burnrate1d                                          | 1           |
9   | apiserver_request:burnrate1h                                          | 1           |
10  | apiserver_request:burnrate2h                                          | 1           |
11  | apiserver_request:burnrate3d                                          | 1           |
12  | apiserver_request:burnrate5m                                          | 1           |
13  | apiserver_request:burnrate6h                                          | 1           |
14  | apiserver_request:burnrate30m                                         | 1           |
15  | cco_credentials_requests_conditions                                   | 5           |
16  | cluster:alertmanager_routing_enabled:max                              | 1           |
17  | cluster_feature_set                                                   | 1           |
18  | cluster_version_available_updates                                     | 1           |
19  | coredns_health_request_duration_seconds_bucket                        | 102         |
20  | coredns_panic_count_total                                             | 6           |
21  | etcd_http_failed_total                                                | 0           |
22  | etcd_http_received_total                                              | 0           |
23  | etcd_http_successful_duration_seconds_bucket                          | 0           |
24  | etcd_network_peer_round_trip_time_seconds_bucket                      | 102         |
25  | etcd_network_peer_sent_failures_total                                 | 3           |
26  | etcd_server_has_leader                                                | 3           |
27  | grpc_client_handled_total                                             | 33          |
28  | grpc_client_started_total                                             | 34          |
29  | grpc_server_handled_total                                             | 2261        |
30  | grpc_server_handling_seconds_bucket                                   | 150         |
31  | grpc_server_started_total                                             | 133         |
32  | haproxy_up                                                            | 2           |
33  | http_request_duration_seconds_bucket                                  | 165         |
34  | http_request_duration_seconds_count                                   | 11          |
35  | image_registry_operator_storage_reconfigured_total                    | 1           |
36  | kubelet_node_name                                                     | 6           |
37  | kubelet_pod_worker_duration_seconds_bucket                            | 144         |
38  | kubeproxy_sync_proxy_rules_duration_seconds_bucket                    | 96          |
39  | kubeproxy_sync_proxy_rules_last_queued_timestamp_seconds              | 0           |
40  | kubeproxy_sync_proxy_rules_last_timestamp_seconds                     | 6           |
41  | kube_daemonset_status_current_number_scheduled                        | 15          |
42  | kube_daemonset_status_number_available                                | 15          |
43  | kube_daemonset_status_number_misscheduled                             | 15          |
44  | kube_daemonset_updated_number_scheduled                               | 15          |
45  | kube_deployment_metadata_generation                                   | 54          |
46  | kube_deployment_spec_replicas                                         | 54          |
47  | kube_deployment_status_observed_generation                            | 54          |
48  | kube_deployment_status_replicas_available                             | 54          |
49  | kube_deployment_status_replicas_updated                               | 54          |
50  | kube_hpa_spec_max_replicas                                            | 0           |
51  | kube_hpa_status_current_replicas                                      | 0           |
52  | kube_hpa_status_desired_replicas                                      | 0           |
53  | kube_job_failed                                                       | 0           |
54  | kube_job_spec_completions                                             | 1           |
55  | kube_job_status_succeeded                                             | 1           |
56  | kube_node_info                                                        | 6           |
57  | kube_node_spec_taint                                                  | 3           |
58  | kube_node_status_allocatable                                          | 42          |
59  | kube_node_status_capacity                                             | 42          |
60  | kube_poddisruptionbudget_status_desired_healthy                       | 2           |
61  | kube_poddisruptionbudget_status_expected_pods                         | 2           |
62  | kube_pod_container_status_last_terminated_reason                      | 2232        |
63  | kube_pod_container_status_restarts_total                              | 372         |
64  | kube_pod_container_status_waiting_reason                              | 2604        | 
65  | kube_pod_status_phase                                                 | 1140        |
66  | kube_pod_status_ready                                                 | 684         |
67  | kube_statefulset_metadata_generation                                  | 2           |
68  | kube_statefulset_replicas                                             | 2           |
69  | kube_statefulset_status_current_revision                              | 2           |
70  | kube_statefulset_status_observed_generation                           | 2           |
71  | kube_statefulset_status_replicas                                      | 2           |
72  | kube_statefulset_status_replicas_ready                                | 2           |
73  | kube_statefulset_status_replicas_updated                              | 2           |
74  | kube_statefulset_status_update_revision                               | 2           |
75  | kube_state_metrics_list_total                                         | 27          |
76  | kube_state_metrics_watch_total                                        | 27          |
77  | mapi_current_pending_csr                                              | 1           |
78  | mapi_machine_created_timestamp_seconds                                | 6           |
79  | mapi_mao_collector_up                                                 | 2           |
80  | mapi_max_pending_csrv                                                 | 1           |
81  | mcd_drain                                                             | 6           |
82  | mcd_kubelet_state                                                     | 6           |
83  | mcd_pivot_err                                                         | 6           |
84  | mcd_reboot_err                                                        | 6           |
85  | prometheus_notifications_queue_capacity                               | 2           |
86  | node_filesystem_files                                                 | 54          |
87  | node_filesystem_files_free                                            | 54          |
88  | node_filesystem_readonly                                              | 54          |
89  | node_md_disks                                                         | 0           |
90  | node_md_disks_required                                                | 0           |
91  | node_network_receive_errs_total                                       | 195         |
92  | node_network_transmit_errs_total                                      | 195         |
93  | node_network_up                                                       | 195         |
94  | node_nf_conntrack_entries                                             | 6           |
95  | node_nf_conntrack_entries_limit                                       | 6           |
96  | node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile | 18          |
97  | node_textfile_scrape_error                                            | 6           |
98  | node_timex_offset_seconds                                             | 6           |
99  | node_timex_sync_status                                                | 6           |
100 | openshift_samples_degraded_info                                       | 1           |
101 | openshift_samples_failed_imagestream_import_info                      | 76          |
102 | openshift_samples_invalidconfig_info                                  | 1           |
103 | openshift_samples_invalidsecret_info                                  | 2           |
104 | openshift_samples_retry_imagestream_import_total                      | 0           |
105 | openshift_samples_tbr_inaccessible_info                               | 1           |
106 | prometheus_notifications_queue_length                                 | 2           |
107 | prometheus_config_last_reload_successful                              | 2           |
108 | prometheus_notifications_alertmanagers_discovered                     | 2           |
109 | prometheus_notifications_errors_total                                 | 6           |
110 | prometheus_notifications_sent_total                                   | 6           |
111 | prometheus_operator_list_operations_failed_total                      | 3           |
112 | prometheus_operator_list_operations_total                             | 3           |
113 | prometheus_operator_node_address_lookup_errors_total                  | 1           |
114 | prometheus_operator_reconcile_errors_total                            | 3           |
115 | prometheus_operator_watch_operations_failed_total                     | 3           |
116 | prometheus_operator_watch_operations_total                            | 3           |
117 | prometheus_remote_storage_failed_samples_total                        | 0           |
118 | prometheus_remote_storage_highest_timestamp_in_seconds                | 2           |
119 | prometheus_remote_storage_queue_highest_sent_timestamp_seconds        | 0           |
120 | prometheus_remote_storage_shards_desired                              | 0           |
121 | prometheus_remote_storage_shards_max                                  | 0           |
122 | prometheus_remote_storage_succeeded_samples_total                     | 0           |
123 | prometheus_rule_evaluation_failures_total                             | 116         |
124 | prometheus_rule_group_iterations_missed_total                         | 116         |
125 | prometheus_target_scrapes_sample_duplicate_timestamp_total            | 2           |
126 | prometheus_target_scrapes_sample_out_of_order_total                   | 2           | 
127 | prometheus_tsdb_compactions_failed_total                              | 2           |
128 | prometheus_tsdb_head_samples_appended_total                           | 2           |
129 | prometheus_tsdb_reloads_failures_total                                | 2           |
130 | template_router_reload_failure                                        | 2           |
131 | thanos_querier_store_apis_dns_failures_total                          | 2           |
132 | thanos_querier_store_apis_dns_lookups_total                           | 2           |
133 | time()-cluster_version_operator_update_retrieval_timestamp_seconds    | 1           |
134 | vector                                                                | 0           |
</details>

Time Series

**Comment by dislbenn** [comment]
> any impact on the performance? Could you list the number of timeseries for those metrics? Thanks

@clyang82 I have listed the time series above.

**Comment by marcolan018** [comment]
@dislbenn 
for the performance impact, is there a spread sheet which contains the number of time series data for each metrics, for both regular cluster and SNO, similar as https://docs.google.com/spreadsheets/d/1PsmFuGhAiAUY0qrmO6cLsHYYqeVptcb-_iqSbijCWdE/edit?ts=6074f041#gid=0?

**Comment by dislbenn** [comment]
> @dislbenn
> for the performance impact, is there a spread sheet which contains the number of time series data for each metrics, for both regular cluster and SNO, similar as https://docs.google.com/spreadsheets/d/1PsmFuGhAiAUY0qrmO6cLsHYYqeVptcb-_iqSbijCWdE/edit?ts=6074f041#gid=0?

Please try this link: https://docs.google.com/spreadsheets/d/1VUnWd-dcutYAVbZIgYmflxvcIJRKTjC6hR36k_T1C_8/edit#gid=1030587416

**Comment by bjoydeep** [comment]
@dislbenn today: @randymgeorge @marcolan018 @subbarao-meduri had a long discussion on this. We agreed that for `now` (point in time statement), we are not going to add more metrics related to the alerts OOTB (except for the ALERTS metric themselves). The reason is 2 fold:
- customer can easily add it if they need to after the install
- there is memory and storage impact on the Hub for metrics being added. and we want to inform the customer about cost of adding metrics so that they can better decide.

**Pull request closed without merging**
