### PR TITLE
update the default interval to 60s

### PR DESCRIPTION
**Pull request by marcolan018**
fix: https://github.com/open-cluster-management/backlog/issues/12622

Signed-off-by: Marco <llan@redhat.com>

### CODE REVIEW

**Comment by marcolan018** [comment]
hold until https://github.com/open-cluster-management/observability-e2e-test/pull/183 merged

/hold

**Comment by songleo** [comment]
@marcolan018 we need to update the doc as well.

**Comment by marcolan018** [comment]
@songleo 
there is a related doc issue for all default values update: https://github.com/open-cluster-management/backlog/issues?q=is%3Aissue+is%3Aopen+label%3Asquad%3Adoc

**Review by songleo — APPROVED** [review]

**Pull request merged**
