### PR TITLE
fix metrics data customization and support run as standalone locally for metrics-collector simulator.

### PR DESCRIPTION
**Pull request by morvencao**
This PR:

- fix metrics data image customization(add recordingrule for simulated metrics)
- support run as standalone process locally for metrics-collector simulator

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
KinD testing will be fixed in https://github.com/open-cluster-management/multicluster-observability-operator/pull/833

**Comment by morvencao** [comment]
@clyang82 PTAL

**Review by clyang82 — APPROVED** [review]
lgtm

**Comment by clyang82** [comment]
the e2e cannot be passed due to https://coreos.slack.com/archives/CSZLMKPS5/p1637647044349100

**Comment by morvencao** [comment]
rebased the code changes.

**Comment by morvencao** [comment]
ref: https://github.com/open-cluster-management/backlog/issues/18241

**Pull request merged**
