### PR TITLE
in non-ocp, disable useless metrics scrape in prometheus

### PR DESCRIPTION
**Pull request by marcolan018**
https://github.com/open-cluster-management/backlog/issues/16110
Signed-off-by: Marco <llan@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
@marcolan018 Do we need to update `scrape_interval` to keep consistent with `interval` of `observabilityAddonSpec`?

**Comment by marcolan018** [comment]
@clyang82 not included in this pr
in fact, we may not update scrape interval for prometheus. Some testing still in progress

**Pull request merged**
