### PR TITLE
add filter for rbac resources and managedclusteraddon in cache.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://github.com/open-cluster-management/backlog/issues/14774

### Add filter for rbac resources(ClusterRole, ClusterRoleBinding, Role and RoleBinding)

in 2000 simulated manifestwork and 2000 simulated managedcluster env:

before:
```
# kubectl -n open-cluster-management top pod -l name=multicluster-observability-operator
NAME                                                  CPU(cores)   MEMORY(bytes)
multicluster-observability-operator-cd77d999f-xs5bc   20m           805Mi
```

After: 
```
# kubectl -n open-cluster-management top pod -l name=multicluster-observability-operator
NAME                                                   CPU(cores)   MEMORY(bytes)
multicluster-observability-operator-86755cb7b4-q7rdn   12m          562Mi
```
image

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Review by marcolan018 — APPROVED** [review]
lgtm

**Comment by morvencao** [comment]
there was a fix to controller-filtered-cache repo: https://github.com/IBM/controller-filtered-cache/pull/30

**Comment by morvencao** [comment]
@clyang82 @marcolan018 Another look?

**Pull request merged**
