### PR TITLE
added fleet level dashboard for SLO status

### PR DESCRIPTION
**Pull request by dislbenn**
Issue: https://github.com/open-cluster-management/backlog/issues/15902

Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

### CODE REVIEW

**Comment by marcolan018** [comment]
@dislbenn 
some related error in unit test, please fix
```
2021/09/22 12:09:11 got file 'dash-k8s-service-level-overview-api-server-cluster.yaml', but '/go/src/github.com/open-cluster-management/multicluster-observability-operator/operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml' must be a directory to be a root
2021/09/22 12:09:11 Cannot find this path /go/src/github.com/open-cluster-management/multicluster-observability-operator/operators/multiclusterobservability/tests/manifests/base/grafana, accumulating resources: merging resources from 'dash-k8s-service-level-overview-api-server-cluster.yaml': may not add resource with an already registered id: ~G_v1_ConfigMap|open-cluster-management-observability|grafana-dashboard-k8s-slo
```

**Comment by dislbenn** [comment]
> @dislbenn
> some related error in unit test, please fix
> 
> ```
> 2021/09/22 12:09:11 got file 'dash-k8s-service-level-overview-api-server-cluster.yaml', but '/go/src/github.com/open-cluster-management/multicluster-observability-operator/operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml' must be a directory to be a root
> 2021/09/22 12:09:11 Cannot find this path /go/src/github.com/open-cluster-management/multicluster-observability-operator/operators/multiclusterobservability/tests/manifests/base/grafana, accumulating resources: merging resources from 'dash-k8s-service-level-overview-api-server-cluster.yaml': may not add resource with an already registered id: ~G_v1_ConfigMap|open-cluster-management-observability|grafana-dashboard-k8s-slo
> ```

Thank you! I just realized that the metadata name needed to be changed.

**Pull request merged**
