### PR TITLE
updated service-level overview dashboard label and descriptions

### PR DESCRIPTION
**Pull request by dislbenn**
Issues: https://github.com/open-cluster-management/backlog/issues/15909 & https://github.com/open-cluster-management/backlog/issues/16201.

The task for updating the dashboard labels: https://github.com/open-cluster-management/backlog/issues/16212.

Related to PR: https://github.com/open-cluster-management/rhacm-docs/pull/2668.

Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

### CODE REVIEW

**Comment by dislbenn** [comment]
For issue [#15909](https://github.com/open-cluster-management/backlog/issues/15909), the changes will update the dashboard titles and description to a more consistent format within the docs.

For issue [#16201](https://github.com/open-cluster-management/backlog/issues/16201), the changes will remove the `relative time` from the panel's title within the dashboard. If the panels are shrunken, the `title` and `relative time` range will overlap. Grafana gives us the option to hide the time range display while keeping the functionality for it. Hiding the time range will remove the redundancy within the panel heading.

Before hiding the `relative time` range.
Screen Shot 2021-09-16 at 11 37 42 AM

After hiding the `relative time` range.
Screen Shot 2021-09-16 at 11 37 04 AM

**Comment by dislbenn** [comment]
@marcolan018 I would like to ask for your help to review. 🙂

**Comment by marcolan018** [comment]
don't recommend to change the default refresh inverval to 1m, because we will change the default scrape interval to 5m. If that, the refresh one is too frequent

**Comment by dislbenn** [comment]
> don't recommend to change the default refresh inverval to 1m, because we will change the default scrape interval to 5m. If that, the refresh one is too frequent

@marcolan018 would you recommend removing the refresh rate, since by default it'll be 5 minutes?

**Comment by dislbenn** [comment]
Reverted the refresh time back to 5m.

**Comment by dislbenn** [comment]
@marcolan018 Does everything seem okay to merge?

**Pull request merged**
