### PR TITLE
replace filesystem panel, change topk cpu usage to bar chart

### PR DESCRIPTION
**Pull request by RobDolares**
Signed-off-by: rhowingt@redhat.com <rhowingt@redhat.com>

Related Issues: 
- https://github.com/open-cluster-management/backlog/issues/12406
- https://github.com/open-cluster-management/backlog/issues/10491

<kbd>Screen Shot 2021-05-26 at 9 37 37 PM</kbd>

### CODE REVIEW

**Comment by marcolan018** [comment]
For top4 memory/diskuage usage panels, will also update later, to be as same as the top5 cpu usage panel, correct?

**Comment by RobDolares** [comment]
> For top5 memory/diskuage usage panels, will also update later, to be as same as the top5 cpu usage panel, correct?

@marcolan018 - updated

**Pull request merged**
