### PR TITLE
cherrypick 669 to cleanup cache for mco cr deletion

### PR DESCRIPTION
**Pull request by morvencao**
Signed-off-by: morvencao <lcao@redhat.com>

cherrypick https://github.com/open-cluster-management/multicluster-observability-operator/pull/669
/hold

### CODE REVIEW

**Comment by clyang82** [comment]
@morvencao you may update to remove `CleanUpImageManifests`

**Comment by morvencao** [comment]
fix: https://github.com/open-cluster-management/backlog/issues/14560

**Pull request merged**
