### PR TITLE
update managedclusteraddon if it's updated during upgrade flow

### PR DESCRIPTION
**Pull request by marcolan018**
https://github.com/open-cluster-management/backlog/issues/13647

Signed-off-by: Marco <llan@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
Do you know why the `installNamespace` is missed during upgrade?

**Comment by marcolan018** [comment]
@clyang82 
installNamespace is a new field added in 2.3

**Comment by clyang82** [comment]
> @clyang82
> installNamespace is a new field added in 2.3

I see. Thanks

**Pull request merged**
