### PR TITLE
fixed resource name

### PR DESCRIPTION
**Pull request by songleo**
- we should have a fixed resource name because  the limits on name length
- https://github.com/open-cluster-management/backlog/issues/12476
Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by marcolan018** [comment]
seems the changes replace all places where mco name are used
for some places, e.g. app.kubernetes.io/instance, value of this label should be mco name, not a fixed prefix?

**Comment by songleo** [comment]
> seems the changes replace all places where mco name are used
> for some places, e.g. app.kubernetes.io/instance, value of this label should be mco name, not a fixed prefix?

yes, you are right, I am working on it. thanks.

**Pull request merged**
