### PR TITLE
update cookie secret for alertmanager proxy.

### PR DESCRIPTION
**Pull request by morvencao**
try to resolve the git leak issue found in https://github.com/open-cluster-management/backlog/issues/12516

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
Looks like the jobs are not triggerred.

**Comment by morvencao** [comment]
@clyang82 Would you take another look at this?
I found simply deleting the `cookie-secret` will report error, so I have to figure out other solution:
passing the cookie secret file mount from the secret and the secret contains randomly generated seed string.
To avoid the infinite reconcile loop, we need to add `skip-creation-if-exist: "true"` annotation.

**Comment by clyang82** [comment]
@haoqing0110 Do we need have the same fix in management-ingress?

**Comment by haoqing0110** [comment]
@clyang82 yes, similar issue to be fixed in https://github.com/open-cluster-management/management-ingress-chart/pull/110

**Pull request merged**
