### PR TITLE
Should not clean image manifests after delete mco cr

### PR DESCRIPTION
**Pull request by clyang82**
ref: https://github.com/open-cluster-management/backlog/issues/14817

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
Is this root cause for https://github.com/open-cluster-management/backlog/issues/14817

**Comment by clyang82** [comment]
Yes. I have appended my comments in that ticket. Please check if it is reasonable.

**Review by morvencao — COMMENTED** [review]
/lgtm

**Pull request merged**
