### PR TITLE
add recording rule for apiserver_request_duration_seconds_bucket

### PR DESCRIPTION
**Pull request by haoqing0110**
Ref https://github.com/open-cluster-management/backlog/issues/11950

Signed-off-by: haoqing0110 <qhao@redhat.com>

### CODE REVIEW

**Review by marcolan018 — CHANGES_REQUESTED** [review]
still missing some changes
1. besides apiserver_request_duration_seconds_bucket, also needs to handle apiserver_request_total as default one
2. needs to update grafana dashboards to use the new metrics

**Comment by haoqing0110** [comment]
@marcolan018  thanks, will create another PR to handle all the record rules.

**Pull request merged**
