### PR TITLE
 support roks

### PR DESCRIPTION
**Pull request by marcolan018**
https://github.com/open-cluster-management/backlog/issues/11120

### CODE REVIEW

**Comment by clyang82** [comment]
@marcolan018 How does klusterlet support roks? Do we follow the same way? Thanks.

**Comment by marcolan018** [comment]
@clyang82 
klusterlet supports roks from 2.2, and in fact, I almost reuse their code.

**Comment by clyang82** [comment]
> @clyang82
> klusterlet supports roks from 2.2, and in fact, I almost reuse their code.

I saw you have logged an issue - https://github.com/open-cluster-management/backlog/issues/11125 against 2.1. since klusterlet supports roks from 2.2, we cannot support it in 2.1 separately. right?

**Comment by marcolan018** [comment]
@clyang82 that's a typo. I changed to 2.2

**Review by songleo — APPROVED** [review]

**Pull request merged**
