### PR TITLE
Add resource requirement  for metrics-collector

### PR DESCRIPTION
**Pull request by songleo**
- Add resource requirement  for metrics-collector and fix https://github.com/open-cluster-management/backlog/issues/5764 
- Add resource requirement  for endpoint-monitoring-operator

Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by songleo** [comment]
need to update doc and api doc

**Comment by marcolan018** [comment]
also need to update here:
https://github.com/open-cluster-management/multicluster-observability-operator/blob/3a97707319781bd40289dc36678448f36fdd457c/controllers/placementrule/manifestwork.go#L314

**Comment by clyang82** [comment]
@songleo Where is the resources from?

**Pull request merged**
