### PR TITLE
delete deprecated roles/manifestworks in 2.2

### PR DESCRIPTION
**Pull request by marcolan018**
1. clean old manifestworks
2. clean old roles: https://github.com/open-cluster-management/backlog/issues/10004

### CODE REVIEW

**Comment by clyang82** [comment]
@marcolan018 I did not follow the comment: `imo, it doesn't matter to delete old manifestworks before/after new manifestworks created. Since work agent will guarantee the state in managed cluster as same as the new manifestworks finally`. for instance, upgrade from 2.2, the old manifestwork is there, the endpoint-operator is in managed cluster. if the new manifestwork created, do we have conflicted between old and new?

**Comment by marcolan018** [comment]
@clyang82 
there will be no conflict
the resource with the same name in new manifestwork will not be created until the old manifestwork deleted.

**Pull request merged**
