### PR TITLE
update label refresh option

### PR DESCRIPTION
**Pull request by RobDolares**
Related issue: https://github.com/open-cluster-management/backlog/issues/14419

Signed-off-by: rhowingt@redhat.com <rhowingt@redhat.com>

### CODE REVIEW

**Comment by marcolan018** [comment]
@RobDolares 
do we need to update all "refresh" : 1 to "refresh" 2, or only need to update the "refresh" which used by a label_value query?

**Comment by RobDolares** [comment]
@marcolan018 
I just replaced all instances - so they will all update with time change, visible or not.  Do you see issue with that?

**Comment by marcolan018** [comment]
@RobDolares 
No, just want to verify. These changes make sense to me. We can merge these change if got approval from release team.

/lgtm
/approve

**Comment by RobDolares** [comment]
@marcolan018 - just following up here.  This is tied to issue deferred from 2.3, are we able to merge or do we still need to hold.

**Comment by marcolan018** [comment]
@RobDolares I think we need to hold it until 2.3 is released
btw, can you create a pr for main branch?

**Comment by clyang82** [comment]
@RobDolares Can we unhold it for release-2.3
@dislbenn Are you able to have it in release-2.2? Thanks.

**Comment by clyang82** [comment]
Need manually create a PR for release-2.2. @dislbenn Can you help it? Thanks.

**Comment by dislbenn** [comment]
> Need manually create a PR for release-2.2. @dislbenn Can you help it? Thanks. 2.2.8 is not open for business now. we can create a PR and merge later.

Yes, I'll work towards opening a PR for release-2.2.

**Comment by dislbenn** [comment]
Here's the PR for `2.2`: https://github.com/open-cluster-management/multicluster-observability-operator/pull/698.

**Pull request merged**
