### PR TITLE
One repo

### PR DESCRIPTION
**Pull request by clyang82**
fixed: https://github.com/open-cluster-management/backlog/issues/14034

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
Are the `COMPONENT_NAME` and `COMPONENT_VERSION` required by the CICD pipeline? do we still need them?

**Comment by clyang82** [comment]
> `COMPONENT_VERSION`

it can be replaced by `OSCI_COMPONENT_NAME` and `OSCI_COMPONENT_VERSION`. for example:
```
    name: branch-ci-open-cluster-management-rbac-query-proxy-release-2.4-publish
    run_if_changed: ^(proxy/.*|pkg/.*)$
    spec:
      containers:
      - args:
        - -f
        - /opt/build-harness/Makefile.build-harness-openshift-ci
        - osci/publish
        command:
        - make
        env:
        - name: OSCI_COMPONENT_NAME
          value: rbac-query-proxy
        - name: OSCI_COMPONENT_VERSION
          value: "2.4"
        - name: OSCI_IMAGE_REMOTE_REPO_SRC
          value: registry.ci.openshift.org/open-cluster-management
        - name: OSCI_PUBLISH_DELAY
          value: "20"
        - name: SELF
          value: make -f /opt/build-harness/Makefile.build-harness-openshift-ci
```

**Review by morvencao — COMMENTED** [review]
/lgtm

I think we can merge since we have cut the release branch, also after this is merged, others can also help to fix issue based on this.

**Pull request merged**
