### PR TITLE
replace image for managedcluster resource for mch update event.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://github.com/open-cluster-management/backlog/issues/15996

- add OR logic for MCH resource update check: the original checks may cause upgrade issue about image replacement.

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
As we discussed offline, please add more UT for this case. Thanks.

**Comment by morvencao** [comment]
@clyang82 PTAL

**Pull request merged**
