### PR TITLE
Use default snapshot for all our images

### PR DESCRIPTION
**Pull request by clyang82**
Update to use default snapshot for all our owned images. We pass the `mco-imageTagSuffix` in e2e test. but the grafana is still using the `quay.io/openshift/origin-grafana:4.8.0`. This PR is to define the default `DefaultImgTagSuffix` only in config.go. so we can use this default value in case cannot replace the correct images.

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
/lgtm

**Comment by clyang82** [comment]
Remove support for loading and deleting dashboard by slug in grafana 8.x https://github.com/grafana/grafana/pull/35104
that is why the `grafana-dev` test can be passed. cannot find the grafana dashboard information by using `127.0.0.1:3001/api/dashboards/db/$dashboard_name`

**Comment by morvencao** [comment]
@clyang82 Is this ready to merge?

**Pull request merged**
