### PR TITLE
Update e2e description to match Polarion test case

### PR DESCRIPTION
**Pull request by quchangl-github**
Signed-off-by: quchangl-github <cqu@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
Did you make changes for `observability_alert_test.go` `observability_config_test.go ` and  `observability_grafana_test.go`?

**Comment by hchenxa** [comment]
@

> Did you make changes for `observability_alert_test.go` `observability_config_test.go ` and `observability_grafana_test.go`? they should be new added files.

the file should under tests/pkg/tests but not the tests/pkg @clyang82

**Pull request merged**
